In [47]:
import pandas as pd

In [48]:
#data = pd.read_csv("2004-2021.tsv", sep="\t")

In [49]:
#data.to_csv('2004-2021.csv',sep=';')

In [50]:
data = pd.read_csv('2004-2021.csv', sep=';')

In [51]:
del data['Unnamed: 0']

In [52]:
data.head(2)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115

In [53]:
data['ESTADO'].unique() #tira as repetiçoes e deixa somente os valores unicos

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

In [54]:
# faz uma comparação elemente a elemento da series, retornando uma series de booleans
data['ESTADO'] == 'SAO PAULO'

0         False
1         False
2         False
3         False
4         False
          ...
120818    False
120819    False
120820     True
120821    False
120822    False
Name: ESTADO, Length: 120823, dtype: bool

In [55]:
#salvando a series de booleans em uma variavel
selecao = data['ESTADO'] == 'SAO PAULO'

In [56]:
#retorna somente os valores da linha da variavel cujo valor seja TRUE
postos_sp = data[selecao]

USANDO LOC

In [57]:
#faz a mesma coisa que a de cima, so retorna os valores TRUE da variavel
data.loc[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120750,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GLP,663,R$/13Kg,85.340,5.292,68.000,99.990,-99999.0,0.062,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120767,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GNV,51,R$/m3,3.150,0.282,2.499,3.797,-99999.0,0.090,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120793,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL,411,R$/l,4.134,0.188,3.699,5.099,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

USANDO O METODO QUERY

In [58]:
#filtra as linhas onde o valor é igual a "SAO PAULO"
data.query('ESTADO == "SAO PAULO"') #pra usar string dentro de outra é preciso usar aspas diferentes

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120750,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GLP,663,R$/13Kg,85.340,5.292,68.000,99.990,-99999.0,0.062,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120767,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GNV,51,R$/m3,3.150,0.282,2.499,3.797,-99999.0,0.090,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120793,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL,411,R$/l,4.134,0.188,3.699,5.099,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [59]:
postos_sp.head(2)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.59,1.15,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.59,1.15,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087

In [60]:
#o python cria uma coluna com os indeces antigos
postos_sp.reset_index(drop=True, inplace= True) #se usar o drop=True dentro dos parenteses o python nao cria essa coluna e o implace true 
#ja faz a modificação direto no dataframe

In [61]:
postos_sp.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098
1,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087
2,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103
3,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112
4,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104

SELECIONANDO POSTOS DO RIO DE JANEIRO COM PRECO ACIMA DE 2 REAIS

In [62]:
data['ESTADO'] == 'RIO DE JANEIRO'

0         False
1         False
2         False
3         False
4         False
          ...
120818    False
120819    False
120820    False
120821    False
120822    False
Name: ESTADO, Length: 120823, dtype: bool

In [63]:
data['PREÇO MÉDIO REVENDA'] > 2.0

0         False
1         False
2         False
3         False
4         False
          ...
120818     True
120819     True
120820     True
120821     True
120822     True
Name: PREÇO MÉDIO REVENDA, Length: 120823, dtype: bool

In [64]:
selecao = (data['ESTADO'] == 'RIO DE JANEIRO') & (data['PREÇO MÉDIO REVENDA'] > 2.0)
selecao

0         False
1         False
2         False
3         False
4         False
          ...
120818    False
120819    False
120820    False
120821    False
120822    False
Length: 120823, dtype: bool

In [65]:
#tras somente os postos que firem True nas duas ocasiões mostradas (estado RJ e preço acima de 2.0)
data[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
2501,2006-02-26,2006-03-04,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,881,R$/l,2.028,0.148,1.589,2.550,0.222,0.073,1.806,0.11,1.31,2.1358,0.061
2528,2006-03-05,2006-03-11,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,889,R$/l,2.125,0.149,1.779,2.550,0.286,0.070,1.839,0.117,1.438,2.2801,0.064
2555,2006-03-12,2006-03-18,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,902,R$/l,2.163,0.138,1.799,2.599,0.268,0.064,1.895,0.134,1.43,2.3454,0.071
2582,2006-03-19,2006-03-25,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,898,R$/l,2.166,0.146,1.760,2.568,0.231,0.067,1.935,0.14,1.438,2.2925,0.072
2609,2006-03-26,2006-04-01,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,890,R$/l,2.172,0.143,1.789,2.550,0.209,0.066,1.963,0.133,1.438,2.2513,0.068
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120717,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,198,R$/l,6.099,0.208,5.480,6.599,-99999.0,0.034,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120744,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GLP,137,R$/13Kg,75.218,5.398,65.000,93.000,-99999.0,0.072,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120763,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GNV,77,R$/m3,3.011,0.385,2.759,4.399,-99999.0,0.128,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120787,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL,72,R$/l,4.290,0.183,3.849,4.599,-99999.0,0.043,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120814,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL S10,155,R$/l,4.302,0.172,3.930,4.699,-99999.0,0.040,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

DARIA PRA FAZER NO METODO QUERY MAS NESSE CASO ESPECIFICO NAO CONSEGUE POIS OS VALORES DA COLUNA PREÇO POSSUI CARACTERES ESPECIAIS

In [66]:
#nao funciona
#data.query('ESTADO == "RIO DE JANEIRO" and PREÇO MÉDIO REVENDA > 2')

In [67]:
data.query('ESTADO == "SAO PAULO" or ESTADO == "RIO DE JANEIRO"')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,0.740,1.890,0.312,0.140,0.786,0.173,0.326,1.263,0.22
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098
49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,0.740,1.499,0.284,0.144,0.808,0.175,0.3257,1.2921,0.217
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087
76,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,973,R$/l,1.103,0.140,0.770,1.589,0.281,0.127,0.822,0.166,0.38909,1.1859,0.202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120767,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GNV,51,R$/m3,3.150,0.282,2.499,3.797,-99999.0,0.090,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120787,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL,72,R$/l,4.290,0.183,3.849,4.599,-99999.0,0.043,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120793,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL,411,R$/l,4.134,0.188,3.699,5.099,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120814,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL S10,155,R$/l,4.302,0.172,3.930,4.699,-99999.0,0.040,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

FAZENDO A COMPARACAO SEM QUE O PROGRAMA PERCORRA 2 VEZES TODO O DATAFRAME PARA AVALIAR AS DUAS CONDICOES E DEPOIS CONCATENA-LAS

In [68]:
selecao_1 = data['ESTADO'] == 'RIO DE JANEIRO'
postos_rj = data[selecao_1]
postos_rj

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,0.740,1.890,0.312,0.140,0.786,0.173,0.326,1.263,0.22
49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,0.740,1.499,0.284,0.144,0.808,0.175,0.3257,1.2921,0.217
76,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,973,R$/l,1.103,0.140,0.770,1.589,0.281,0.127,0.822,0.166,0.38909,1.1859,0.202
103,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,955,R$/l,1.149,0.156,0.799,1.599,0.3,0.136,0.849,0.188,0.3453,1.3667,0.221
130,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,966,R$/l,1.165,0.154,0.830,1.599,0.254,0.132,0.911,0.198,0.4,1.3667,0.217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120717,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,198,R$/l,6.099,0.208,5.480,6.599,-99999.0,0.034,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120744,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GLP,137,R$/13Kg,75.218,5.398,65.000,93.000,-99999.0,0.072,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120763,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GNV,77,R$/m3,3.011,0.385,2.759,4.399,-99999.0,0.128,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120787,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL,72,R$/l,4.290,0.183,3.849,4.599,-99999.0,0.043,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120814,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL S10,155,R$/l,4.302,0.172,3.930,4.699,-99999.0,0.040,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [69]:
selecao_2 = postos_rj['PREÇO MÉDIO REVENDA'] > 2

In [70]:
postos_rj_preco_maior_que_2 = postos_rj[selecao_2]

In [71]:
postos_rj_preco_maior_que_2

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
2501,2006-02-26,2006-03-04,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,881,R$/l,2.028,0.148,1.589,2.550,0.222,0.073,1.806,0.11,1.31,2.1358,0.061
2528,2006-03-05,2006-03-11,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,889,R$/l,2.125,0.149,1.779,2.550,0.286,0.070,1.839,0.117,1.438,2.2801,0.064
2555,2006-03-12,2006-03-18,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,902,R$/l,2.163,0.138,1.799,2.599,0.268,0.064,1.895,0.134,1.43,2.3454,0.071
2582,2006-03-19,2006-03-25,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,898,R$/l,2.166,0.146,1.760,2.568,0.231,0.067,1.935,0.14,1.438,2.2925,0.072
2609,2006-03-26,2006-04-01,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,890,R$/l,2.172,0.143,1.789,2.550,0.209,0.066,1.963,0.133,1.438,2.2513,0.068
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120717,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,198,R$/l,6.099,0.208,5.480,6.599,-99999.0,0.034,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120744,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GLP,137,R$/13Kg,75.218,5.398,65.000,93.000,-99999.0,0.072,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120763,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GNV,77,R$/m3,3.011,0.385,2.759,4.399,-99999.0,0.128,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120787,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL,72,R$/l,4.290,0.183,3.849,4.599,-99999.0,0.043,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120814,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL S10,155,R$/l,4.302,0.172,3.930,4.699,-99999.0,0.040,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

Selecione registro de postos de SP e RJ com gasolina comum acima de r$2,00

Jeito mais lento, percorrendo o dataset mais vezes

In [73]:
selecao_1 = (data['ESTADO'] == 'SAO PAULO' ) | (data['ESTADO'] == 'RIO DE JANEIRO' ) #se é sao paulo ou rio de janeiro

In [77]:
selecao_2 = (data['PRODUTO'] == 'GASOLINA COMUM')

In [79]:
selecao_3 = (data['PREÇO MÉDIO REVENDA'] > 2)

In [81]:
selecao_final = selecao_1 & selecao_2 & selecao_3

In [82]:
selecao_final

0         False
1         False
2         False
3         False
4         False
          ...
120818    False
120819    False
120820    False
120821    False
120822    False
Length: 120823, dtype: bool

In [84]:
#SOMENTE RIO E SAO PAULO, GASOLINA COMUM E PREÇO DE REVENDA MAIOR QUE 2,00
data_filtrado = data[selecao_final]

In [86]:
print(data_filtrado['ESTADO'].unique())
print(data_filtrado['PRODUTO'].unique())

['RIO DE JANEIRO' 'SAO PAULO']
['GASOLINA COMUM']

Forma mais rapida

In [87]:
#apenas os postos de rio de janeiro e sao paulo
postos_sp_rj = data[selecao_1]

In [88]:
postos_sp_rj

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,0.740,1.890,0.312,0.140,0.786,0.173,0.326,1.263,0.22
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098
49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,0.740,1.499,0.284,0.144,0.808,0.175,0.3257,1.2921,0.217
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087
76,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,973,R$/l,1.103,0.140,0.770,1.589,0.281,0.127,0.822,0.166,0.38909,1.1859,0.202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120767,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GNV,51,R$/m3,3.150,0.282,2.499,3.797,-99999.0,0.090,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120787,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL,72,R$/l,4.290,0.183,3.849,4.599,-99999.0,0.043,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120793,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL,411,R$/l,4.134,0.188,3.699,5.099,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120814,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL S10,155,R$/l,4.302,0.172,3.930,4.699,-99999.0,0.040,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [91]:
#fazer uma comparaçao somente em cima desse df sp e rj
selecao_2 = (postos_sp_rj['PRODUTO'] == 'GASOLINA COMUM')
selecao_2

22        False
23        False
49        False
50        False
76        False
          ...
120767    False
120787    False
120793    False
120814    False
120820    False
Name: PRODUTO, Length: 9638, dtype: bool

In [92]:
#apenas registros de sp e rj com gasolina comum
postos_sp_rj_gasolina = postos_sp_rj[selecao_2]
postos_sp_rj_gasolina

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,1.700,2.599,0.254,0.053,1.791,0.047,1.6363,1.9594,0.026
12087,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,GASOLINA COMUM,4107,R$/l,1.891,0.101,1.570,2.399,0.235,0.053,1.656,0.064,1.38,1.944,0.039
12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,1.700,2.599,0.252,0.055,1.788,0.049,1.5943,1.99651,0.027
12114,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,GASOLINA COMUM,4133,R$/l,1.888,0.101,1.540,2.220,0.233,0.053,1.655,0.063,1.38,1.9319,0.038
12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,1.700,2.599,0.252,0.053,1.79,0.046,1.63596,2.2137,0.026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120366,2021-04-11,2021-04-17,SUDESTE,SAO PAULO,GASOLINA COMUM,1058,R$/l,5.206,0.234,3.899,5.999,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120538,2021-04-18,2021-04-24,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,240,R$/l,6.071,0.217,5.399,6.599,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120544,2021-04-18,2021-04-24,SUDESTE,SAO PAULO,GASOLINA COMUM,1075,R$/l,5.205,0.216,4.199,5.999,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120717,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,198,R$/l,6.099,0.208,5.480,6.599,-99999.0,0.034,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [97]:
selecao_3 = (postos_sp_rj_gasolina['PREÇO MÉDIO REVENDA'] > 2)

In [99]:
postos_rj_preco_gasolina_maior_que_2 = postos_sp_rj_gasolina[selecao_3]

In [100]:
postos_rj_preco_gasolina_maior_que_2

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,1.700,2.599,0.254,0.053,1.791,0.047,1.6363,1.9594,0.026
12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,1.700,2.599,0.252,0.055,1.788,0.049,1.5943,1.99651,0.027
12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,1.700,2.599,0.252,0.053,1.79,0.046,1.63596,2.2137,0.026
12167,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.053,0.111,1.730,2.599,0.251,0.054,1.802,0.055,1.64,2.21425,0.031
12194,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.063,0.107,1.760,2.599,0.247,0.052,1.816,0.054,1.64,2.32425,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120366,2021-04-11,2021-04-17,SUDESTE,SAO PAULO,GASOLINA COMUM,1058,R$/l,5.206,0.234,3.899,5.999,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120538,2021-04-18,2021-04-24,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,240,R$/l,6.071,0.217,5.399,6.599,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120544,2021-04-18,2021-04-24,SUDESTE,SAO PAULO,GASOLINA COMUM,1075,R$/l,5.205,0.216,4.199,5.999,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120717,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,198,R$/l,6.099,0.208,5.480,6.599,-99999.0,0.034,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

SELECIONANDO REGISTROS DOS ANOS DE 2008 2010 E 2012

ALTERNATIVA 1

In [101]:
data.head(2)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115

In [112]:
data['DATA INICIAL']

0         2004-05-09
1         2004-05-09
2         2004-05-09
3         2004-05-09
4         2004-05-09
             ...
120818    2021-04-25
120819    2021-04-25
120820    2021-04-25
120821    2021-04-25
120822    2021-04-25
Name: DATA INICIAL, Length: 120823, dtype: object

In [114]:
data['ANO'] = data['DATA INICIAL'].str.extract(r'(\d{4})')

In [116]:
del data['Ano']

In [118]:
data.head(2)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,2004

In [121]:
data['ANO'].unique()

array(['2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021'], dtype=object)

In [124]:
data['ANO'] = data['ANO'].astype(int)

In [125]:
#cria uma variavel alocando todas as comparações 
selecao = (data['ANO'] == 2008) | (data['ANO'] == 2010) | (data['ANO'] == 2012)

In [127]:
selecao

0         False
1         False
2         False
3         False
4         False
          ...
120818    False
120819    False
120820    False
120821    False
120822    False
Name: ANO, Length: 120823, dtype: bool

In [130]:
data[selecao]['ANO'].unique()

array([2008, 2010, 2012])

ALTERNATIVA 2

In [131]:
lista_de_anos = [2008, 2010, 2012]

In [134]:
#retorna uma series de booleanos
selecao = data['ANO'].isin(lista_de_anos)
selecao

0         False
1         False
2         False
3         False
4         False
          ...
120818    False
120819    False
120820    False
120821    False
120822    False
Name: ANO, Length: 120823, dtype: bool

In [135]:
data[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO
5098,2008-01-06,2008-01-12,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,1.806,0.082,1.709,1.950,0.29,0.045,1.516,0.061,1.3892,1.6157,0.04,2008
5099,2008-01-06,2008-01-12,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.616,0.100,1.470,1.899,0.293,0.062,1.323,0.05,1.2242,1.6173,0.038,2008
5100,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,142,R$/l,1.581,0.095,1.390,1.850,0.278,0.060,1.303,0.073,1.14,1.45,0.056,2008
5101,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,133,R$/l,1.831,0.046,1.680,1.910,0.382,0.025,1.449,0.044,1.3247,1.5514,0.03,2008
5102,2008-01-06,2008-01-12,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,1.699,0.098,1.530,1.999,0.199,0.058,1.5,0.062,1.39,1.7689,0.041,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55754,2012-12-30,2013-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,17,R$/m3,1.891,0.015,1.860,1.900,0.466,0.008,1.425,0.098,1.2657,1.4789,0.069,2012
55755,2012-12-30,2013-01-05,SUL,RIO GRANDE DO SUL,GNV,34,R$/m3,1.980,0.040,1.919,2.140,0.566,0.020,1.414,0.028,1.3997,1.4608,0.02,2012
55756,2012-12-30,2013-01-05,SUL,SANTA CATARINA,GNV,41,R$/m3,2.003,0.034,1.879,2.099,-,0.017,-,-,-,-,-,2012
55757,2012-12-30,2013-01-05,SUDESTE,SAO PAULO,GNV,82,R$/m3,1.598,0.199,1.399,2.599,0.397,0.125,1.201,0.182,0.8354,1.535,0.152,2012
55758,2012-12-30,2013-01-05,NORDESTE,SERGIPE,GNV,11,R$/m3,1.847,0.033,1.790,1.899,0.504,0.018,1.343,0.178,1.1253,1.543,0.133,2012

**ALTERNATIVA 3**

Utilizando o query

In [136]:
lista_de_anos

[2008, 2010, 2012]

In [138]:
data.query('ANO in @lista_de_anos') #o @ é usado quando se refere a uma variavel

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO
5098,2008-01-06,2008-01-12,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,1.806,0.082,1.709,1.950,0.29,0.045,1.516,0.061,1.3892,1.6157,0.04,2008
5099,2008-01-06,2008-01-12,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.616,0.100,1.470,1.899,0.293,0.062,1.323,0.05,1.2242,1.6173,0.038,2008
5100,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,142,R$/l,1.581,0.095,1.390,1.850,0.278,0.060,1.303,0.073,1.14,1.45,0.056,2008
5101,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,133,R$/l,1.831,0.046,1.680,1.910,0.382,0.025,1.449,0.044,1.3247,1.5514,0.03,2008
5102,2008-01-06,2008-01-12,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,1.699,0.098,1.530,1.999,0.199,0.058,1.5,0.062,1.39,1.7689,0.041,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55754,2012-12-30,2013-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,17,R$/m3,1.891,0.015,1.860,1.900,0.466,0.008,1.425,0.098,1.2657,1.4789,0.069,2012
55755,2012-12-30,2013-01-05,SUL,RIO GRANDE DO SUL,GNV,34,R$/m3,1.980,0.040,1.919,2.140,0.566,0.020,1.414,0.028,1.3997,1.4608,0.02,2012
55756,2012-12-30,2013-01-05,SUL,SANTA CATARINA,GNV,41,R$/m3,2.003,0.034,1.879,2.099,-,0.017,-,-,-,-,-,2012
55757,2012-12-30,2013-01-05,SUDESTE,SAO PAULO,GNV,82,R$/m3,1.598,0.199,1.399,2.599,0.397,0.125,1.201,0.182,0.8354,1.535,0.152,2012
55758,2012-12-30,2013-01-05,NORDESTE,SERGIPE,GNV,11,R$/m3,1.847,0.033,1.790,1.899,0.504,0.018,1.343,0.178,1.1253,1.543,0.133,2012

**USANDO FOR** com o DataFrame.iterrows()

In [140]:
for index, row in data.head(10). iterrows():
    print(f'indece {index} ==> {row}')

indece 0 ==> DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                           DISTRITO FEDERAL
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  127
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.288
DESVIO PADRÃO REVENDA                       0.016
PREÇO MÍNIMO REVENDA                         1.19
PREÇO MÁXIMO REVENDA                         1.35
MARGEM MÉDIA REVENDA                        0.463
COEF DE VARIAÇÃO REVENDA                    0.012
PREÇO MÉDIO DISTRIBUIÇÃO                    0.825
DESVIO PADRÃO DISTRIBUIÇÃO                   0.11
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.4201
PREÇO MÁXIMO DISTRIBUIÇÃO                  0.9666
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.133
ANO                                          2004
Name: 0, dtype: object
indece 1 ==> DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
ANO                                          2004
Name: 1, dtype: object
indece 2 ==> DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                MATO GROSSO
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  192
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.389
DESVIO PADRÃO REVENDA                       0.097
PREÇO MÍNIMO REVENDA                         1.18
PREÇO MÁXIMO REVENDA                         1.76
MARGEM MÉDIA REVENDA                        0.419
COEF DE VARIAÇÃO REVENDA                     0.07
PREÇO MÉDIO DISTRIBUIÇÃO                     0.97
DESVIO PADRÃO DISTRIBUIÇÃO                  0.095
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5614
PREÇO MÁXIMO DISTRIBUIÇÃO                   1.161
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.098
ANO                                          2004
Name: 2, dtype: object
indece 3 ==> DATA INICIAL                             2004-05-09
DATA FINAL                               2004-05-15
REGIÃO                                 CENTRO OESTE
ESTADO                           MATO GROSSO DO SUL
PRODUTO                            ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                    162
UNIDADE DE MEDIDA                              R$/l
PREÇO MÉDIO REVENDA                           1.262
DESVIO PADRÃO REVENDA                          0.07
PREÇO MÍNIMO REVENDA                           1.09
PREÇO MÁXIMO REVENDA                          1.509
MARGEM MÉDIA REVENDA                          0.432
COEF DE VARIAÇÃO REVENDA                      0.055
PREÇO MÉDIO DISTRIBUIÇÃO                       0.83
DESVIO PADRÃO DISTRIBUIÇÃO                    0.119
PREÇO MÍNIMO DISTRIBUIÇÃO                    0.5991
PREÇO MÁXIMO DISTRIBUIÇÃO                   1.22242
COEF DE VARIAÇÃO DISTRIBUIÇÃO                 0.143
ANO                                            2004
Name: 3, dtype: object
indece 4 ==> DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                                   NORDESTE
ESTADO                                    ALAGOAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  103
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.181
DESVIO PADRÃO REVENDA                       0.078
PREÇO MÍNIMO REVENDA                         1.05
PREÇO MÁXIMO REVENDA                          1.4
MARGEM MÉDIA REVENDA                         0.24
COEF DE VARIAÇÃO REVENDA                    0.066
PREÇO MÉDIO DISTRIBUIÇÃO                    0.941
DESVIO PADRÃO DISTRIBUIÇÃO                  0.077
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.7441
PREÇO MÁXIMO DISTRIBUIÇÃO                  1.0317
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.082
ANO                                          2004
Name: 4, dtype: object
indece 5 ==> DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                                   NORDESTE
ESTADO                                      BAHIA
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  408
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.383
DESVIO PADRÃO REVENDA                       0.132
PREÇO MÍNIMO REVENDA                        0.999
PREÇO MÁXIMO REVENDA                         2.05
MARGEM MÉDIA REVENDA                        0.426
COEF DE VARIAÇÃO REVENDA                    0.095
PREÇO MÉDIO DISTRIBUIÇÃO                    0.957
DESVIO PADRÃO DISTRIBUIÇÃO                  0.128
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5686
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.35
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.134
ANO                                          2004
Name: 5, dtype: object
indece 6 ==> DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                                   NORDESTE
ESTADO                                      CEARA
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  278
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.453
DESVIO PADRÃO REVENDA                       0.218
PREÇO MÍNIMO REVENDA                         1.03
PREÇO MÁXIMO REVENDA                         1.95
MARGEM MÉDIA REVENDA                        0.353
COEF DE VARIAÇÃO REVENDA                     0.15
PREÇO MÉDIO DISTRIBUIÇÃO                      1.1
DESVIO PADRÃO DISTRIBUIÇÃO                  0.068
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.7332
PREÇO MÁXIMO DISTRIBUIÇÃO                   1.294
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.062
ANO                                          2004
Name: 6, dtype: object
indece 7 ==> DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                                   NORDESTE
ESTADO                                   MARANHAO
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  105
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.631
DESVIO PADRÃO REVENDA                       0.158
PREÇO MÍNIMO REVENDA                         1.35
PREÇO MÁXIMO REVENDA                          2.0
MARGEM MÉDIA REVENDA                        0.515
COEF DE VARIAÇÃO REVENDA                    0.097
PREÇO MÉDIO DISTRIBUIÇÃO                    1.116
DESVIO PADRÃO DISTRIBUIÇÃO                  0.091
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.9923
PREÇO MÁXIMO DISTRIBUIÇÃO                 1.36183
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.082
ANO                                          2004
Name: 7, dtype: object
indece 8 ==> DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                                   NORDESTE
ESTADO                                    PARAIBA
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  125
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.284
DESVIO PADRÃO REVENDA                        0.13
PREÇO MÍNIMO REVENDA                          1.1
PREÇO MÁXIMO REVENDA                        1.699
MARGEM MÉDIA REVENDA                        0.353
COEF DE VARIAÇÃO REVENDA                    0.101
PREÇO MÉDIO DISTRIBUIÇÃO                    0.931
DESVIO PADRÃO DISTRIBUIÇÃO                  0.072
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.7577
PREÇO MÁXIMO DISTRIBUIÇÃO                  1.2972
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.077
ANO                                          2004
Name: 8, dtype: object
indece 9 ==> DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                                   NORDESTE
ESTADO                                 PERNAMBUCO
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  423
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.224
DESVIO PADRÃO REVENDA                       0.141
PREÇO MÍNIMO REVENDA                        0.989
PREÇO MÁXIMO REVENDA                          1.7
MARGEM MÉDIA REVENDA                        0.277
COEF DE VARIAÇÃO REVENDA                    0.115
PREÇO MÉDIO DISTRIBUIÇÃO                    0.947
DESVIO PADRÃO DISTRIBUIÇÃO                  0.091
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5643
PREÇO MÁXIMO DISTRIBUIÇÃO                  1.3541
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.096
ANO                                          2004
Name: 9, dtype: object

In [142]:
for index, row in data.head(10). iterrows():
    print(f'indece {index} ==> {row["ESTADO"]}')

indece 0 ==> DISTRITO FEDERAL
indece 1 ==> GOIAS
indece 2 ==> MATO GROSSO
indece 3 ==> MATO GROSSO DO SUL
indece 4 ==> ALAGOAS
indece 5 ==> BAHIA
indece 6 ==> CEARA
indece 7 ==> MARANHAO
indece 8 ==> PARAIBA
indece 9 ==> PERNAMBUCO