In [5]:
import pandas as pd

In [6]:
#data = pd.read_csv("2004-2021.tsv", sep="\t")

In [7]:
#data.to_csv('2004-2021.csv',sep=';')

In [9]:
data = pd.read_csv('2004-2021.csv', sep=';')

In [14]:
del data['Unnamed: 0']

In [16]:
data.head(2)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115

In [19]:
data['ESTADO'].unique() #tira as repetiçoes e deixa somente os valores unicos

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

In [20]:
# faz uma comparação elemente a elemento da series, retornando uma series de booleans
data['ESTADO'] == 'SAO PAULO'

0         False
1         False
2         False
3         False
4         False
          ...
120818    False
120819    False
120820     True
120821    False
120822    False
Name: ESTADO, Length: 120823, dtype: bool

In [21]:
#salvando a series de booleans em uma variavel
selecao = data['ESTADO'] == 'SAO PAULO'

In [27]:
#retorna somente os valores da linha da variavel cujo valor seja TRUE
postos_sp = data[selecao]

USANDO LOC

In [25]:
#faz a mesma coisa que a de cima, so retorna os valores TRUE da variavel
data.loc[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120750,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GLP,663,R$/13Kg,85.340,5.292,68.000,99.990,-99999.0,0.062,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120767,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GNV,51,R$/m3,3.150,0.282,2.499,3.797,-99999.0,0.090,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120793,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL,411,R$/l,4.134,0.188,3.699,5.099,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

USANDO O METODO QUERY

In [26]:
#filtra as linhas onde o valor é igual a "SAO PAULO"
data.query('ESTADO == "SAO PAULO"') #pra usar string dentro de outra é preciso usar aspas diferentes

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120750,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GLP,663,R$/13Kg,85.340,5.292,68.000,99.990,-99999.0,0.062,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120767,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GNV,51,R$/m3,3.150,0.282,2.499,3.797,-99999.0,0.090,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120793,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL,411,R$/l,4.134,0.188,3.699,5.099,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [28]:
postos_sp.head(2)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.59,1.15,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.59,1.15,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087

In [35]:
#o python cria uma coluna com os indeces antigos
postos_sp.reset_index(drop=True, inplace= True) #se usar o drop=True dentro dos parenteses o python nao cria essa coluna e o implace true 
#ja faz a modificação direto no dataframe

In [34]:
postos_sp.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098
1,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087
2,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103
3,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112
4,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104

SELECIONANDO POSTOS DO RIO DE JANEIRO COM PRECO ACIMA DE 2 REAIS

In [36]:
data['ESTADO'] == 'RIO DE JANEIRO'

0         False
1         False
2         False
3         False
4         False
          ...
120818    False
120819    False
120820    False
120821    False
120822    False
Name: ESTADO, Length: 120823, dtype: bool

In [37]:
data['PREÇO MÉDIO REVENDA'] > 2.0

0         False
1         False
2         False
3         False
4         False
          ...
120818     True
120819     True
120820     True
120821     True
120822     True
Name: PREÇO MÉDIO REVENDA, Length: 120823, dtype: bool

In [39]:
selecao = (data['ESTADO'] == 'RIO DE JANEIRO') & (data['PREÇO MÉDIO REVENDA'] > 2.0)
selecao

0         False
1         False
2         False
3         False
4         False
          ...
120818    False
120819    False
120820    False
120821    False
120822    False
Length: 120823, dtype: bool

In [40]:
#tras somente os postos que firem True nas duas ocasiões mostradas (estado RJ e preço acima de 2.0)
data[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
2501,2006-02-26,2006-03-04,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,881,R$/l,2.028,0.148,1.589,2.550,0.222,0.073,1.806,0.11,1.31,2.1358,0.061
2528,2006-03-05,2006-03-11,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,889,R$/l,2.125,0.149,1.779,2.550,0.286,0.070,1.839,0.117,1.438,2.2801,0.064
2555,2006-03-12,2006-03-18,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,902,R$/l,2.163,0.138,1.799,2.599,0.268,0.064,1.895,0.134,1.43,2.3454,0.071
2582,2006-03-19,2006-03-25,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,898,R$/l,2.166,0.146,1.760,2.568,0.231,0.067,1.935,0.14,1.438,2.2925,0.072
2609,2006-03-26,2006-04-01,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,890,R$/l,2.172,0.143,1.789,2.550,0.209,0.066,1.963,0.133,1.438,2.2513,0.068
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120717,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,198,R$/l,6.099,0.208,5.480,6.599,-99999.0,0.034,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120744,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GLP,137,R$/13Kg,75.218,5.398,65.000,93.000,-99999.0,0.072,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120763,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GNV,77,R$/m3,3.011,0.385,2.759,4.399,-99999.0,0.128,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120787,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL,72,R$/l,4.290,0.183,3.849,4.599,-99999.0,0.043,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120814,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL S10,155,R$/l,4.302,0.172,3.930,4.699,-99999.0,0.040,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

DARIA PRA FAZER NO METODO QUERY MAS NESSE CASO ESPECIFICO NAO CONSEGUE POIS OS VALORES DA COLUNA PREÇO POSSUI CARACTERES ESPECIAIS

In [ ]:
#nao funciona
#data.query('ESTADO == "RIO DE JANEIRO" and PREÇO MÉDIO REVENDA > 2')

In [41]:
data.query('ESTADO == "SAO PAULO" or ESTADO == "RIO DE JANEIRO"')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,0.740,1.890,0.312,0.140,0.786,0.173,0.326,1.263,0.22
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098
49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,0.740,1.499,0.284,0.144,0.808,0.175,0.3257,1.2921,0.217
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087
76,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,973,R$/l,1.103,0.140,0.770,1.589,0.281,0.127,0.822,0.166,0.38909,1.1859,0.202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120767,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GNV,51,R$/m3,3.150,0.282,2.499,3.797,-99999.0,0.090,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120787,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL,72,R$/l,4.290,0.183,3.849,4.599,-99999.0,0.043,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120793,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL,411,R$/l,4.134,0.188,3.699,5.099,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120814,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL S10,155,R$/l,4.302,0.172,3.930,4.699,-99999.0,0.040,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

FAZENDO A COMPARACAO SEM QUE O PROGRAMA PERCORRA 2 VEZES TODO O DATAFRAME PARA AVALIAR AS DUAS CONDICOES E DEPOIS CONCATENA-LAS

In [42]:
selecao_1 = data['ESTADO'] == 'RIO DE JANEIRO'
postos_rj = data[selecao_1]
postos_rj

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,0.740,1.890,0.312,0.140,0.786,0.173,0.326,1.263,0.22
49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,0.740,1.499,0.284,0.144,0.808,0.175,0.3257,1.2921,0.217
76,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,973,R$/l,1.103,0.140,0.770,1.589,0.281,0.127,0.822,0.166,0.38909,1.1859,0.202
103,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,955,R$/l,1.149,0.156,0.799,1.599,0.3,0.136,0.849,0.188,0.3453,1.3667,0.221
130,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,966,R$/l,1.165,0.154,0.830,1.599,0.254,0.132,0.911,0.198,0.4,1.3667,0.217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120717,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,198,R$/l,6.099,0.208,5.480,6.599,-99999.0,0.034,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120744,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GLP,137,R$/13Kg,75.218,5.398,65.000,93.000,-99999.0,0.072,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120763,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GNV,77,R$/m3,3.011,0.385,2.759,4.399,-99999.0,0.128,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120787,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL,72,R$/l,4.290,0.183,3.849,4.599,-99999.0,0.043,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120814,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL S10,155,R$/l,4.302,0.172,3.930,4.699,-99999.0,0.040,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [44]:
selecao_2 = postos_rj['PREÇO MÉDIO REVENDA'] > 2

In [45]:
postos_rj_preco_maior_que_2 = postos_rj[selecao_2]

In [46]:
postos_rj_preco_maior_que_2

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
2501,2006-02-26,2006-03-04,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,881,R$/l,2.028,0.148,1.589,2.550,0.222,0.073,1.806,0.11,1.31,2.1358,0.061
2528,2006-03-05,2006-03-11,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,889,R$/l,2.125,0.149,1.779,2.550,0.286,0.070,1.839,0.117,1.438,2.2801,0.064
2555,2006-03-12,2006-03-18,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,902,R$/l,2.163,0.138,1.799,2.599,0.268,0.064,1.895,0.134,1.43,2.3454,0.071
2582,2006-03-19,2006-03-25,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,898,R$/l,2.166,0.146,1.760,2.568,0.231,0.067,1.935,0.14,1.438,2.2925,0.072
2609,2006-03-26,2006-04-01,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,890,R$/l,2.172,0.143,1.789,2.550,0.209,0.066,1.963,0.133,1.438,2.2513,0.068
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120717,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,198,R$/l,6.099,0.208,5.480,6.599,-99999.0,0.034,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120744,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GLP,137,R$/13Kg,75.218,5.398,65.000,93.000,-99999.0,0.072,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120763,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GNV,77,R$/m3,3.011,0.385,2.759,4.399,-99999.0,0.128,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120787,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL,72,R$/l,4.290,0.183,3.849,4.599,-99999.0,0.043,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120814,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL S10,155,R$/l,4.302,0.172,3.930,4.699,-99999.0,0.040,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0